### ISSUE TITLE
Change to use OO Statsd clients

### ISSUE THREAD

**Issue by robrwo** [bluefeet/Starch-Plugin-Net-Statsd#1]
You may want to change this to use OO statsd clients like
- Net::Statsd::Client
- Etsy::Statsd
- Net::Statsd::Tiny
- Net::Statsd::Lite

and allow an existing object to be passed in, or to specify the preferred client class (in case the application is already using one of the above).

**Comment by bluefeet** [comment]
This plugin is specifically for `Net::Statsd`, not other modules. We could make a `Starch::Plugin::Statsd` which would do like you suggest, but I generally avoided making "all the things" modules in Starch as it makes dependencies vague and its cleaner to have a separate plugin per module anyways, even if it is a little more work.

Passing in a pre-built object would definitely be a good idea if someone goes about and makes a plugin which wraps one of the OO statsd clients, existing Starch plugins all work this way (they take either a pre-instantiated object or arguments to create one).
